[package]
name = "new-year-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
gstreamer = "0.21.2"
gstreamer-app = "0.21.2"
gstreamer-video = "0.21.2"
rayon = "1.8.0"

serde = { version = "1.0.190", features = ["derive"] }
toml = "0.8.6"

fontdue = { version = "0.7.3", features = ["parallel", "rayon"] }
hhmmss = "0.1.0"
